import { Store, Category, Product, Menu, MenuSection } from '@/types';

export const DEFAULT_STORE: Store = {
  id: 'store-001',
  owner_id: 'user-001',
  name: 'Somtum House (ส้มตำเฮาส์)',
  slug: 'somtum-house',
  logo_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500&auto=format&fit=crop&q=80',
  description: 'อาหารไทย-อีสาน รสชาติต้นตำรับ แซ่บจัดจ้าน คัดสรรวัตถุดิบคุณภาพดีทุกวัน',
  bank_name: 'SCB (ไทยพาณิชย์)',
  bank_account_name: 'Mark',
  bank_account_number: '44324343244',
  promptpay_number: '0812345678',
  status: 'active',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'cat-01',
    store_id: 'store-001',
    name: 'เมนูแนะนำ',
    sort_order: 1,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-02',
    store_id: 'store-001',
    name: 'ส้มตำ & ลาบ',
    sort_order: 2,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-03',
    store_id: 'store-001',
    name: 'อาหารจานเดียว',
    sort_order: 3,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-04',
    store_id: 'store-001',
    name: 'เครื่องดื่ม',
    sort_order: 4,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-05',
    store_id: 'store-001',
    name: 'ของหวาน',
    sort_order: 5,
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEFAULT_PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    store_id: 'store-001',
    category_id: 'cat-01',
    name: 'ส้มตำไทยไข่เค็ม',
    description: 'ส้มตำไทยรสจัดจ้าน คลุกเคล้าไข่เค็มไชยาชั้นดี หวานนำเปรี้ยวตาม โรยถั่วลิสงคั่วหอมกรอบ มะละกอกรอบสดใหม่',
    image_url: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&auto=format&fit=crop&q=80',
    sale_price: 79,
    regular_price: 95,
    status: 'active',
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    option_groups: [
      {
        id: 'optg-01',
        product_id: 'prod-01',
        name: 'ระดับความเผ็ด',
        sort_order: 1,
        options: [
          { id: 'opt-01', option_group_id: 'optg-01', name: 'พริก 1 เม็ด (เผ็ดน้อย)', additional_price: 0, sort_order: 1 },
          { id: 'opt-02', option_group_id: 'optg-01', name: 'พริก 3 เม็ด (เผ็ดกลาง)', additional_price: 0, sort_order: 2 },
          { id: 'opt-03', option_group_id: 'optg-01', name: 'พริก 5 เม็ด (เผ็ดมาก)', additional_price: 0, sort_order: 3 },
          { id: 'opt-04', option_group_id: 'optg-01', name: 'พริก 10 เม็ด (เผ็ดพ่นไฟ)', additional_price: 5, sort_order: 4 },
        ],
      },
      {
        id: 'optg-02',
        product_id: 'prod-01',
        name: 'Topping เพิ่มเติม',
        sort_order: 2,
        options: [
          { id: 'opt-05', option_group_id: 'optg-02', name: 'เพิ่มไข่เค็ม 1 ฟอง', additional_price: 15, sort_order: 1 },
          { id: 'opt-06', option_group_id: 'optg-02', name: 'กุ้งสด 3 ตัว', additional_price: 40, sort_order: 2 },
          { id: 'opt-07', option_group_id: 'optg-02', name: 'หมูยออุบล', additional_price: 25, sort_order: 3 },
        ],
      },
    ],
  },
  {
    id: 'prod-02',
    store_id: 'store-001',
    category_id: 'cat-01',
    name: 'ข้าวผัดกุ้งสดทรงเครื่อง',
    description: 'ข้าวหอมมะลิผัดกระทะร้อนไฟแรง หอมกลิ่นกระทะ ใส่กุ้งสดตัวโต เนื้อเด้งหวาน เสิร์ฟพร้อมต้นหอม แตงกวา และมะนาวสด',
    image_url: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&auto=format&fit=crop&q=80',
    sale_price: 89,
    regular_price: 109,
    status: 'active',
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    option_groups: [
      {
        id: 'optg-03',
        product_id: 'prod-02',
        name: 'ขนาดจาน',
        sort_order: 1,
        options: [
          { id: 'opt-08', option_group_id: 'optg-03', name: 'ธรรมดา', additional_price: 0, sort_order: 1 },
          { id: 'opt-09', option_group_id: 'optg-03', name: 'พิเศษ', additional_price: 20, sort_order: 2 },
          { id: 'opt-10', option_group_id: 'optg-03', name: 'Jumbo (จุใจ)', additional_price: 40, sort_order: 3 },
        ],
      },
      {
        id: 'optg-04',
        product_id: 'prod-02',
        name: 'Topping',
        sort_order: 2,
        options: [
          { id: 'opt-11', option_group_id: 'optg-04', name: 'ไข่ดาวกรอบ', additional_price: 15, sort_order: 1 },
          { id: 'opt-12', option_group_id: 'optg-04', name: 'ไข่เจียวหมูสับ', additional_price: 25, sort_order: 2 },
          { id: 'opt-13', option_group_id: 'optg-04', name: 'กุ้งเพิ่ม 2 ตัว', additional_price: 35, sort_order: 3 },
        ],
      },
    ],
  },
  {
    id: 'prod-03',
    store_id: 'store-001',
    category_id: 'cat-02',
    name: 'ไก่ย่างเขาสวนกวางสมุนไพร',
    description: 'ไก่ย่างหมักสมุนไพรสูตรเฉพาะ ย่างไฟอ่อนจนหนังกรอบเนื้อนุ่ม ชุ่มฉ่ำ เสิร์ฟพร้อมน้ำจิ้มแจ่วรสเด็ด',
    image_url: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=800&auto=format&fit=crop&q=80',
    sale_price: 120,
    regular_price: 150,
    status: 'active',
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    option_groups: [
      {
        id: 'optg-05',
        product_id: 'prod-03',
        name: 'ขนาด',
        sort_order: 1,
        options: [
          { id: 'opt-14', option_group_id: 'optg-05', name: 'ครึ่งตัว', additional_price: 0, sort_order: 1 },
          { id: 'opt-15', option_group_id: 'optg-05', name: 'เต็มตัว', additional_price: 110, sort_order: 2 },
        ],
      },
    ],
  },
  {
    id: 'prod-04',
    store_id: 'store-001',
    category_id: 'cat-03',
    name: 'ผัดไทยกุ้งสดแม่น้ำ',
    description: 'เส้นจันท์เหนียวนุ่ม ผัดซอสมะขามสูตรโบราณเข้มข้น ใส่กุ้งสด เต้าหู้เหลือง ไชโป๊ว กุ้งแห้ง และถั่วงอกกรอบ',
    image_url: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=800&auto=format&fit=crop&q=80',
    sale_price: 99,
    regular_price: 120,
    status: 'active',
    sort_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-05',
    store_id: 'store-001',
    category_id: 'cat-04',
    name: 'ชาไทยเย็นโบราณ เข้มข้น',
    description: 'ชาไทยแท้คัดสรรใบชาเข้มข้น หอมมันกลมกล่อมด้วยนมสดแท้ ชงสดแก้วต่อแก้ว',
    image_url: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800&auto=format&fit=crop&q=80',
    sale_price: 45,
    regular_price: null,
    status: 'active',
    sort_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    option_groups: [
      {
        id: 'optg-06',
        product_id: 'prod-05',
        name: 'ระดับความหวาน',
        sort_order: 1,
        options: [
          { id: 'opt-16', option_group_id: 'optg-06', name: 'หวานปกติ 100%', additional_price: 0, sort_order: 1 },
          { id: 'opt-17', option_group_id: 'optg-06', name: 'หวานน้อย 50%', additional_price: 0, sort_order: 2 },
          { id: 'opt-18', option_group_id: 'optg-06', name: 'ไม่หวาน 0%', additional_price: 0, sort_order: 3 },
        ],
      },
    ],
  },
  {
    id: 'prod-06',
    store_id: 'store-001',
    category_id: 'cat-04',
    name: 'กาแฟสดโบราณ',
    description: 'กาแฟคั่วบดเข้มข้น หอมกรุ่นเอกลักษณ์กาแฟโบราณ รสเข้มหวานมันกลมกล่อม',
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
    sale_price: 55,
    regular_price: null,
    status: 'active',
    sort_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-07',
    store_id: 'store-001',
    category_id: 'cat-04',
    name: 'น้ำดื่มสมุนไพรเก๊กฮวย',
    description: 'เก๊กฮวยแท้ต้มใหม่ทุกวัน หวานละมุนชื่นใจ ดับกระหาย คลายร้อน',
    image_url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&auto=format&fit=crop&q=80',
    sale_price: 25,
    regular_price: null,
    status: 'active',
    sort_order: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEFAULT_MENU_SECTIONS: MenuSection[] = [
  {
    id: 'sec-01',
    menu_id: 'menu-001',
    type: 'logo',
    sort_order: 1,
    content: {},
    styles: {
      width: 90,
      alignment: 'center',
      borderRadius: 999,
      margin: { top: 24, right: 0, bottom: 8, left: 0 },
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
    },
  },
  {
    id: 'sec-02',
    menu_id: 'menu-001',
    type: 'store_name',
    sort_order: 2,
    content: {},
    styles: {
      fontSize: 26,
      fontWeight: 700,
      color: '#18181B',
      textAlign: 'center',
      lineHeight: 1.3,
      letterSpacing: -0.5,
      margin: { top: 4, right: 0, bottom: 4, left: 0 },
      padding: { top: 0, right: 0, bottom: 0, left: 0 },
    },
  },
  {
    id: 'sec-03',
    menu_id: 'menu-001',
    type: 'description',
    sort_order: 3,
    content: {},
    styles: {
      fontSize: 14,
      fontWeight: 400,
      color: '#71717A',
      textAlign: 'center',
      lineHeight: 1.5,
      letterSpacing: 0,
      margin: { top: 0, right: 0, bottom: 16, left: 0 },
      padding: { top: 0, right: 16, bottom: 0, left: 16 },
    },
  },
  {
    id: 'sec-04',
    menu_id: 'menu-001',
    type: 'image',
    sort_order: 4,
    content: {
      url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1600&auto=format&fit=crop&q=80',
      alt: 'Banner เมนูอาหารแนะนำ',
    },
    styles: {
      width: '100%',
      aspectRatio: '16:9',
      objectFit: 'cover',
      borderRadius: 16,
      alignment: 'center',
      margin: { top: 0, right: 0, bottom: 20, left: 0 },
      padding: { top: 0, right: 12, bottom: 0, left: 12 },
    },
  },
  {
    id: 'sec-05',
    menu_id: 'menu-001',
    type: 'category_slider',
    sort_order: 5,
    content: {
      showAll: true,
      allLabel: 'ทั้งหมด',
    },
    styles: {
      tabStyle: 'pill',
      activeTabBgColor: '#FF5A36',
      activeTabTextColor: '#FFFFFF',
      inactiveTabBgColor: '#F4F4F5',
      inactiveTabTextColor: '#52525B',
      alignment: 'center',
      margin: { top: 0, right: 0, bottom: 12, left: 0 },
      padding: { top: 0, right: 16, bottom: 0, left: 16 },
    },
  },
  {
    id: 'sec-06',
    menu_id: 'menu-001',
    type: 'text',
    sort_order: 6,
    content: {
      text: '✨ เมนูซิกเนเจอร์ & อาหารแนะนำ',
    },
    styles: {
      fontSize: 20,
      fontWeight: 700,
      color: '#18181B',
      textAlign: 'left',
      lineHeight: 1.4,
      letterSpacing: -0.3,
      margin: { top: 12, right: 0, bottom: 12, left: 0 },
      padding: { top: 0, right: 16, bottom: 0, left: 16 },
    },
  },
  {
    id: 'sec-07',
    menu_id: 'menu-001',
    type: 'product_list',
    sort_order: 7,
    content: {
      productIds: ['prod-01', 'prod-02', 'prod-03', 'prod-04'],
      display: 'image-text-price',
    },
    styles: {
      gap: 16,
      productNameFontSize: 16,
      productNameColor: '#18181B',
      priceFontSize: 16,
      priceColor: '#FF5A36',
      regularPriceColor: '#A1A1AA',
      borderRadius: 14,
      imageRatio: '1:1',
      margin: { top: 0, right: 0, bottom: 24, left: 0 },
      padding: { top: 0, right: 16, bottom: 0, left: 16 },
    },
  },
  {
    id: 'sec-08',
    menu_id: 'menu-001',
    type: 'text',
    sort_order: 8,
    content: {
      text: '🧋 เครื่องดื่ม & ชาชงสด',
    },
    styles: {
      fontSize: 18,
      fontWeight: 700,
      color: '#18181B',
      textAlign: 'left',
      lineHeight: 1.4,
      letterSpacing: -0.2,
      margin: { top: 16, right: 0, bottom: 8, left: 0 },
      padding: { top: 0, right: 16, bottom: 0, left: 16 },
    },
  },
  {
    id: 'sec-09',
    menu_id: 'menu-001',
    type: 'product_list',
    sort_order: 9,
    content: {
      productIds: ['prod-05', 'prod-06', 'prod-07'],
      display: 'text-price',
    },
    styles: {
      gap: 12,
      productNameFontSize: 15,
      productNameColor: '#27272A',
      priceFontSize: 15,
      priceColor: '#18181B',
      margin: { top: 0, right: 0, bottom: 32, left: 0 },
      padding: { top: 8, right: 16, bottom: 16, left: 16 },
    },
  },
];

export const DEFAULT_MENU: Menu = {
  id: 'menu-001',
  store_id: 'store-001',
  name: 'Somtum House Digital Menu',
  slug: 'somtum-house',
  status: 'published',
  published_at: new Date().toISOString(),
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  sections: DEFAULT_MENU_SECTIONS,
};
